import struct
import socket
from matplotlib.animation import FuncAnimation
import matplotlib.pyplot as plt

sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM)

struct_fmt_header = '@3I'
struct_fmt_body = '2I'

VERSION = 'I'
TRANSDUCER_FREQ = 'I'
SAMPLING_FREQ = 'I'
BURST_NUMBER = 'I'
RANGE = 'I'
GAIN = 'i'
TVG = 'i'
RESERVED1 = 'i'
RESERVED2 = 'i'
YEAR = 'i'
MONTH = 'i'
DAY = 'i'
HOUR = 'i'
MINUTE = 'i'
SEC = 'f'
LATI = 'd'
LONGI = 'd'
RESERVED3 = 'f'
RESERVED4 = 'f'
RESERVED5 = 'f'
RESERVED6 = 'f'
RESERVED7 = 'f'
RESERVED8 = 'f'
RESERVED9 = 'f'
RESERVED10 = '10i'
DATA_TYPE = 'I'
CHANNEL_COUNT = 'I'
DATA_COUNT = 'I'

START_FLAG = 'i'
PACKET_LENGTH = 'i'
MSG_ID = 'i'
VALUE_1 = 'i'
VALUE_2 = 'i'

START_PACKET = 'i'

print(struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VALUE_1+VALUE_2))

print(struct.pack(START_FLAG+PACKET_LENGTH+MSG_ID+VALUE_1+VALUE_2,*(0x5A5A5A5A,struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VALUE_1+VALUE_2),2,1,0)))

print(struct.calcsize(VERSION+TRANSDUCER_FREQ+SAMPLING_FREQ+BURST_NUMBER+RANGE+GAIN+TVG+RESERVED1+RESERVED2+YEAR+MONTH+DAY+HOUR+MINUTE+SEC+LATI+LONGI+RESERVED3+RESERVED4+RESERVED5+RESERVED6+RESERVED7+RESERVED8+RESERVED9+RESERVED10+DATA_TYPE+CHANNEL_COUNT+DATA_COUNT))

print(struct.calcsize(LATI))
sock.bind(('127.0.0.1',9090))
sock.listen()

client_sock, client_addr = sock.accept()

client_sock.send(struct.pack(START_FLAG+PACKET_LENGTH+MSG_ID+VALUE_1+VALUE_2,*(0x5A5A5A5A,struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VALUE_1+VALUE_2),2,1,0)))

unpacked = struct.unpack(struct_fmt_header+struct_fmt_body,client_sock.recv(struct.calcsize(struct_fmt_header+struct_fmt_body)))

print(unpacked)

print(struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VERSION+TRANSDUCER_FREQ+SAMPLING_FREQ+BURST_NUMBER+RANGE+GAIN+TVG+RESERVED1+RESERVED2+YEAR+MONTH+DAY+HOUR+MINUTE+SEC+LATI+LONGI+RESERVED3+RESERVED4+RESERVED5+RESERVED6+RESERVED7+RESERVED8+RESERVED9+RESERVED10+DATA_TYPE+CHANNEL_COUNT+DATA_COUNT))

while True:

    unapcked = struct.unpack(START_FLAG+PACKET_LENGTH+MSG_ID+VERSION+TRANSDUCER_FREQ+SAMPLING_FREQ+BURST_NUMBER+RANGE+GAIN+TVG+RESERVED1+RESERVED2+YEAR+MONTH+DAY+HOUR+MINUTE+SEC+LATI+LONGI+RESERVED3+RESERVED4+RESERVED5+RESERVED6+RESERVED7+RESERVED8+RESERVED9+RESERVED10+DATA_TYPE+CHANNEL_COUNT+DATA_COUNT,client_sock.recv(struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VERSION+TRANSDUCER_FREQ+SAMPLING_FREQ+BURST_NUMBER+RANGE+GAIN+TVG+RESERVED1+RESERVED2+YEAR+MONTH+DAY+HOUR+MINUTE+SEC+LATI+LONGI+RESERVED3+RESERVED4+RESERVED5+RESERVED6+RESERVED7+RESERVED8+RESERVED9+RESERVED10+DATA_TYPE+CHANNEL_COUNT+DATA_COUNT)))

    print(unapcked)

    print(len(unapcked))


    Data_Length = unapcked[1]-struct.calcsize(START_FLAG+PACKET_LENGTH+MSG_ID+VERSION+TRANSDUCER_FREQ+SAMPLING_FREQ+BURST_NUMBER+RANGE+GAIN+TVG+RESERVED1+RESERVED2+YEAR+MONTH+DAY+HOUR+MINUTE+SEC+LATI+LONGI+RESERVED3+RESERVED4+RESERVED5+RESERVED6+RESERVED7+RESERVED8+RESERVED9+RESERVED10+DATA_TYPE+CHANNEL_COUNT+DATA_COUNT)

    CH1_RAWDATA = ''
    CH2_RAWDATA = ''
    if unapcked[37] == 1:
        CH1_RAWDATA = '%iB'%unapcked[39]
        CH2_RAWDATA = '%iB'%unapcked[39]
    elif unapcked[37] == 2:
        CH1_RAWDATA = '%iH'%unapcked[39]
        CH2_RAWDATA = '%iH'%unapcked[39]

    CH1_RAWDATA = struct.unpack(CH1_RAWDATA,client_sock.recv(unapcked[37]*unapcked[39]))

    CH2_RAWDATA = struct.unpack(CH2_RAWDATA,client_sock.recv(unapcked[37]*unapcked[39]))

    print(CH1_RAWDATA)

    print(CH2_RAWDATA)

    client_sock.close()

    break

plt.plot(CH1_RAWDATA)
plt.plot(CH2_RAWDATA)
plt.show()